name: Zip and Publish Artifact

on: push

jobs:
  zip-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get package version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Bundle module
        run: |
          zip -r ${{ github.event.repository.name }}.zip languages scripts styles templates LICENSE module.json package.json README.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.repository.name }}.zip
          name: "${{ github.event.repository.name }} - version ${{ env.version }}"
          make_latest: true
          tag_name: version ${{ env.version }}
          generate_release_notes: true
